### ISSUE TITLE
Problems while scrolling -> Palette?

### ISSUE THREAD

**Issue by timbremer** [Supremez/OL-Wallpapers#1]
> 01-23 18:11:43.225  10609-10609/com.arthurmb.recyclerviewtest E/AndroidRuntime﹕ FATAL 
> EXCEPTION: main
>     Process: com.arthurmb.recyclerviewtest, PID: 10609
>     java.lang.NullPointerException: Attempt to read from field 'android.graphics.Bitmap com.koushikdutta.ion.bitmap.BitmapInfo.bitmap' on a null object reference
>             at com.arthurmb.recyclerviewtest.views.adapters.BookAdapter$1.onCompleted(BookAdapter.java:74)
>             at com.arthurmb.recyclerviewtest.views.adapters.BookAdapter$1.onCompleted(BookAdapter.java:70)
>             at com.koushikdutta.async.future.SimpleFuture.handleCallbackUnlocked(SimpleFuture.java:107)
>             at com.koushikdutta.async.future.SimpleFuture.setComplete(SimpleFuture.java:141)
>             at com.koushikdutta.async.future.SimpleFuture.setComplete(SimpleFuture.java:128)
>             at com.koushikdutta.ion.ImageViewFutureImpl$2.onCompleted(ImageViewFutureImpl.java:86)
>             at com.koushikdutta.ion.ImageViewFutureImpl$2.onCompleted(ImageViewFutureImpl.java:73)
>             at com.koushikdutta.async.future.SimpleFuture.handleCallbackUnlocked(SimpleFuture.java:107)
>             at com.koushikdutta.async.future.SimpleFuture.cancelInternal(SimpleFuture.java:44)
>             at com.koushikdutta.async.future.SimpleFuture.cancel(SimpleFuture.java:54)
>             at com.koushikdutta.async.future.SimpleCancellable.reset(SimpleCancellable.java:81)
>             at com.koushikdutta.async.future.SimpleFuture.reset(SimpleFuture.java:198)
>             at com.koushikdutta.ion.IonImageViewRequestBuilder.intoImageView(IonImageViewRequestBuilder.java:151)
>             at com.koushikdutta.ion.IonRequestBuilder.intoImageView(IonRequestBuilder.java:819)
>             at com.arthurmb.recyclerviewtest.views.adapters.BookAdapter.onBindViewHolder(BookAdapter.java:68)
>             at com.arthurmb.recyclerviewtest.views.adapters.BookAdapter.onBindViewHolder(BookAdapter.java:28)
>             at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:4138)
>             at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:3448)
>             at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:3340)
>             at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1810)
>             at android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:356)
>             at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1269)
>             at android.support.v7.widget.LinearLayoutManager.scrollBy(LinearLayoutManager.java:1097)
>             at android.support.v7.widget.LinearLayoutManager.scrollVerticallyBy(LinearLayoutManager.java:957)
>             at android.support.v7.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:2797)
>             at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
>             at android.view.Choreographer.doCallbacks(Choreographer.java:580)
>             at android.view.Choreographer.doFrame(Choreographer.java:549)
>             at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
>             at android.os.Handler.handleCallback(Handler.java:739)
>             at android.os.Handler.dispatchMessage(Handler.java:95)
>             at android.os.Looper.loop(Looper.java:135)
>             at android.app.ActivityThread.main(ActivityThread.java:5255)
>             at java.lang.reflect.Method.invoke(Native Method)
>             at java.lang.reflect.Method.invoke(Method.java:372)
>             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
>             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)

**Comment by timbremer** [comment]
Solved by @arturomb21
